### ISSUE TITLE
never read thetacut cov?

### ISSUE THREAD

**Issue by pmcdonal** [mathildepinon/desi_fiber_collisions#1]
It looks like you need another {} to put in the thetacut part if present? As it stands it seems it never reads thetacut covariance... (similar for sculpt version below)
https://github.com/mathildepinon/desi_fiber_collisions/blob/377092a66ee021bc47f7b291b3145f1816994a64/bin/emulator_fit.py#L226

**Comment by mathildepinon** [comment]
Ah yes thanks! I fixed it.
